use std::sync::Arc;
use std::sync::Mutex;
use serde::{Serialize, Deserialize};
use gotham_derive::StateData;
use chrono::offset::TimeZone;

#[derive(Serialize, Deserialize)]
pub struct Resto {
    pub id: String,
    pub name: String,
    pub hours: String,
    pub location: String,
}

#[derive(Serialize, Deserialize)]
pub struct MenuItem {
    pub id: String,
    pub id_resto: String,
    pub name: String,
    pub description: String,
    pub vege: bool,
    pub price: f32,
}

#[derive(Serialize, Deserialize)]
pub struct Order {
    pub id: String,
    pub menu_item_ids: Vec<String>,
    pub date: chrono::DateTime<chrono::Local>,
}

#[derive(Serialize, Deserialize)]
pub struct Position {
    lat: f64,
    lon: f64,
    alt: f64,
    accv: f64,
    accr: f64,
    speed: f64,
}

pub struct Data {
    pub restos: Vec<Resto>,
    pub plats: Vec<MenuItem>,
    pub orders: Vec<Order>,
    pub delivery_pos: Position,
}

#[derive(Clone, StateData)]
pub struct AppData {
    pub data: Arc<Mutex<Data>>,
}

impl AppData {
    pub fn new() -> Self {
        // TODO: Remove mock data :)
        let restos = vec![
            Resto {
                id: "0".to_string(),
                name: "Navier - Stokes".to_string(),
                hours: "7h à 19h".to_string(),
                location: "1ᵉʳ étage du pavillon principal".to_string(),
            },
            Resto {
                id: "1".to_string(),
                name: "Hamilton".to_string(),
                hours: "11h à 14h30".to_string(),
                location: "1ᵉʳ étage du pavillon principal".to_string(),
            },
            Resto {
                id: "2".to_string(),
                name: "Galileo".to_string(),
                hours: "7h30 à 19h".to_string(),
                location: "2ⁱᵉᵐᵉ étage du pavillon principal".to_string(),
            },
            Resto {
                id: "3".to_string(),
                name: "Curie".to_string(),
                hours: "11h à 14h (fermé le vendredi)".to_string(),
                location: "6ⁱᵉᵐᵉ étage du pavillon principal".to_string(),
            },
            Resto {
                id: "4".to_string(),
                name: "Hertz".to_string(),
                hours: "du lundi au jeudi de 8h à 14h30".to_string(),
                location: "1ᵉʳ étage du pavillon Lassonde".to_string(),
            },
            Resto {
                id: "5".to_string(),
                name: "Pascal".to_string(),
                hours: "8h à 15h30".to_string(),
                location: "6ⁱᵉᵐᵉ étage du pavillon Lassonde".to_string(),
            }
        ];

        let plats = vec![
            MenuItem {
                id: "0".to_string(),
                id_resto: "2".to_string(),
                name: "Salade repas paysanne".to_string(),
                description: "Jambon et oeufs".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "1".to_string(),
                id_resto: "2".to_string(),
                name: "Salade repas océane".to_string(),
                description: "poisson".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "3".to_string(),
                id_resto: "2".to_string(),
                name: "Salade repas végétarienne".to_string(),
                description: "du vert".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "4".to_string(),
                id_resto: "2".to_string(),
                name: "Salade composée d'orzo".to_string(),
                description: "Orzo, pommes Empire, céleri vert, persil, emmental, concombres, menthe, vinaigrette miel & citron".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "5".to_string(),
                id_resto: "2".to_string(),
                name: "Salade composée légumineuses".to_string(),
                description: "Mélange de légumineuses, poivrons rouges, maïs en grains, céleri, écha-lotes vertes, tomates, vinaigrette balsamique".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "6".to_string(),
                id_resto: "2".to_string(),
                name: "Salade composée riz 7 grains".to_string(),
                description: "Riz 7 grains, ratatouille de légumes grillés, oignons rouges, ail, fines herbes".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "7".to_string(),
                id_resto: "2".to_string(),
                name: "Sandwich ciabatta végétarien".to_string(),
                description: "Pain ciabatta betterave, tempeh mariné, salade de choux et carottes, coriandre fraiche, sauce gingembre".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "8".to_string(),
                id_resto: "2".to_string(),
                name: "Sandwich panini jambon".to_string(),
                description: "Pain panini, jambon blanc, cheddar fort, salade, mayon-naise moutardée".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "9".to_string(),
                id_resto: "2".to_string(),
                name: "Sandwich panini poulet grillé".to_string(),
                description: "Pain panini, poulet grillé, tomates, salade, cheddard blanc, mayonnaise tomates séchées".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "10".to_string(),
                id_resto: "2".to_string(),
                name: "Sandwich panini roti de boeuf".to_string(),
                description: "Pain panini carottes, rôti de bœuf, oignons caramélisés, salade, rémoulade céleri & carottes".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "11".to_string(),
                id_resto: "2".to_string(),
                name: "Sandwich panini roti de porc".to_string(),
                description: "Pain panini, rôti de porc, cornichons à l’aneth, salade, cheddar fort, mayonnaise moutardée".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "12".to_string(),
                id_resto: "2".to_string(),
                name: "Sandwich au jambon".to_string(),
                description: "Simple".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "13".to_string(),
                id_resto: "2".to_string(),
                name: "Sandwich au poulet".to_string(),
                description: "Simple".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "14".to_string(),
                id_resto: "2".to_string(),
                name: "Sandwich au oeufs".to_string(),
                description: "Simple".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "15".to_string(),
                id_resto: "2".to_string(),
                name: "Bol kale kimchi".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "16".to_string(),
                id_resto: "2".to_string(),
                name: "Bol kale toscana".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "17".to_string(),
                id_resto: "2".to_string(),
                name: "Bol fèves noires".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "18".to_string(),
                id_resto: "2".to_string(),
                name: "Bol kale césar".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "19".to_string(),
                id_resto: "2".to_string(),
                name: "Wrap dragon".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "20".to_string(),
                id_resto: "2".to_string(),
                name: "Wrap tempeh bbq".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "21".to_string(),
                id_resto: "2".to_string(),
                name: "Wrap végépaté".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "22".to_string(),
                id_resto: "2".to_string(),
                name: "Wrap mekong".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "23".to_string(),
                id_resto: "3".to_string(),
                name: "Gamma veau éffiloché".to_string(),
                description: "Pain au maïs, veau éffiloché, oignon rouge, carotte, tomate, salade, sauce tzatziki".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "24".to_string(),
                id_resto: "3".to_string(),
                name: "Gamma falafel".to_string(),
                description: "Pain au maïs, falafels, oignon rouge, carotte, tomate, salade, sauce tzatziki".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "25".to_string(),
                id_resto: "3".to_string(),
                name: "Salade repas paysanne".to_string(),
                description: "Jambon & oeufs".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "26".to_string(),
                id_resto: "3".to_string(),
                name: "Salade repas océane".to_string(),
                description: "Poisson".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "27".to_string(),
                id_resto: "3".to_string(),
                name: "Salade repas végétarienne".to_string(),
                description: "".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "28".to_string(),
                id_resto: "3".to_string(),
                name: "Salade composée orzo".to_string(),
                description: "Orzo, pommes Empire, céleri vert, persil, emmental, concombres, menthe, vinaigrette miel & citron".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "29".to_string(),
                id_resto: "3".to_string(),
                name: "Salade composée légumineuses".to_string(),
                description: "Mélange de légumineuses, poivrons rouges, maïs en grains, céleri, échalotes vertes, tomates, vinaigrette balsamique".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "30".to_string(),
                id_resto: "3".to_string(),
                name: "Salade composée riz 7 grains".to_string(),
                description: "Riz 7 grains, ratatouille de légumes grillés, oignons rouges, ail, fines herbes".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "31".to_string(),
                id_resto: "3".to_string(),
                name: "Sandwich au jambon".to_string(),
                description: "Simple".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "32".to_string(),
                id_resto: "3".to_string(),
                name: "Sandwich au poulet".to_string(),
                description: "Simple".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "33".to_string(),
                id_resto: "3".to_string(),
                name: "Sandwich au oeufs".to_string(),
                description: "Simple".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "34".to_string(),
                id_resto: "3".to_string(),
                name: "Bol kale kimchi".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "35".to_string(),
                id_resto: "3".to_string(),
                name: "Bol kale toscana".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "36".to_string(),
                id_resto: "3".to_string(),
                name: "Bol fèves noires".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "37".to_string(),
                id_resto: "3".to_string(),
                name: "Bol kale césar".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "38".to_string(),
                id_resto: "3".to_string(),
                name: "Wrap dragon".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "39".to_string(),
                id_resto: "3".to_string(),
                name: "Wrap tempeh bbq".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "40".to_string(),
                id_resto: "3".to_string(),
                name: "Wrap végépaté".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "41".to_string(),
                id_resto: "3".to_string(),
                name: "Wrap mekong".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "42".to_string(),
                id_resto: "0".to_string(),
                name: "Toast".to_string(),
                description: "pain".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "43".to_string(),
                id_resto: "0".to_string(),
                name: "Muffin anglais".to_string(),
                description: "pain".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "44".to_string(),
                id_resto: "0".to_string(),
                name: "Grilled cheese".to_string(),
                description: "pain".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "45".to_string(),
                id_resto: "0".to_string(),
                name: "Sandwich déjeuner".to_string(),
                description: "Œuf, jambon, bacon, salade, tomate. Avec café ou jus de 200ml ou lait 2%.".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "46".to_string(),
                id_resto: "0".to_string(),
                name: "Sandwich muffin".to_string(),
                description: "Œuf, jambon, bacon, fromage. Avec café ou jus de 200ml ou lait 2%.".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "47".to_string(),
                id_resto: "0".to_string(),
                name: "Poutine déjeuner".to_string(),
                description: "Pommes de terre, œuf, fromage, bacon & sauce hollandaise".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "48".to_string(),
                id_resto: "0".to_string(),
                name: "L’assiette brunch".to_string(),
                description: "Pommes de terre, 2 viandes, 2 œufs, fèves au lard, salade et tomate + extra cretons. Avec café ou jus de 200ml ou lait 2%.".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "49".to_string(),
                id_resto: "0".to_string(),
                name: "L'assiette déjeuner 1".to_string(),
                description: "1 œuf, rôties. Avec café ou jus de 200ml ou lait 2%.".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "50".to_string(),
                id_resto: "0".to_string(),
                name: "L'assiette déjeuner 2".to_string(),
                description: "1 viande, 1 œuf, rôties. Avec café ou jus de 200ml ou lait 2%.".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "51".to_string(),
                id_resto: "0".to_string(),
                name: "L'assiette déjeuner 3".to_string(),
                description: "Pommes de terre, 1 viande, 1 œuf, rôties. Avec café ou jus de 200ml ou lait 2%.".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "52".to_string(),
                id_resto: "0".to_string(),
                name: "L'assiette déjeuner 4".to_string(),
                description: "Pommes de terre, 2 viandes, 1 œuf, rôties. Avec café ou jus de 200ml ou lait 2%.".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "53".to_string(),
                id_resto: "0".to_string(),
                name: "Crème de légumes".to_string(),
                description: "Soupe".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "54".to_string(),
                id_resto: "0".to_string(),
                name: "Soupe toscane & chou frisé".to_string(),
                description: "Soupe".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "55".to_string(),
                id_resto: "0".to_string(),
                name: "Cari aux légumes & dattes".to_string(),
                description: "Plat principal".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "56".to_string(),
                id_resto: "0".to_string(),
                name: "Chili à la viande gratiné".to_string(),
                description: "Plat principal".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "57".to_string(),
                id_resto: "0".to_string(),
                name: "Mignon de porc aux olives".to_string(),
                description: "Plat principal".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "58".to_string(),
                id_resto: "0".to_string(),
                name: "Riz pilaf".to_string(),
                description: "Féculents".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "59".to_string(),
                id_resto: "0".to_string(),
                name: "Légumes".to_string(),
                description: "Légumes".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "60".to_string(),
                id_resto: "0".to_string(),
                name: "Salade du moment".to_string(),
                description: "Légumes".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "61".to_string(),
                id_resto: "0".to_string(),
                name: "Desserts du jour".to_string(),
                description: "Dessert".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "62".to_string(),
                id_resto: "1".to_string(),
                name: "Pizza pointe 3 fromages".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "63".to_string(),
                id_resto: "1".to_string(),
                name: "Pizza pointe pepperoni & fromages".to_string(),
                description: "".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "64".to_string(),
                id_resto: "1".to_string(),
                name: "Pizza pointe végétarienne".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "65".to_string(),
                id_resto: "1".to_string(),
                name: "Pâtes".to_string(),
                description: "Penne ou linguine, sauce rosée ou sauce tomate à la viande ou sauce tomate basilic, parmesan ou mozzarella".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "66".to_string(),
                id_resto: "1".to_string(),
                name: "Tiramisu".to_string(),
                description: "Dessert".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "67".to_string(),
                id_resto: "1".to_string(),
                name: "Gâteau aux fruits de la passion & mangue".to_string(),
                description: "Dessert".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "68".to_string(),
                id_resto: "4".to_string(),
                name: "Salade repas paysanne".to_string(),
                description: "Jambon et oeufs".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "69".to_string(),
                id_resto: "4".to_string(),
                name: "Salade repas océane".to_string(),
                description: "poisson".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "70".to_string(),
                id_resto: "4".to_string(),
                name: "Salade repas végétarienne".to_string(),
                description: "du vert".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "71".to_string(),
                id_resto: "4".to_string(),
                name: "Salade composée d'orzo".to_string(),
                description: "Orzo, pommes Empire, céleri vert, persil, emmental, concombres, menthe, vinaigrette miel & citron".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "72".to_string(),
                id_resto: "4".to_string(),
                name: "Salade composée légumineuses".to_string(),
                description: "Mélange de légumineuses, poivrons rouges, maïs en grains, céleri, écha-lotes vertes, tomates, vinaigrette balsamique".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "73".to_string(),
                id_resto: "4".to_string(),
                name: "Salade composée riz 7 grains".to_string(),
                description: "Riz 7 grains, ratatouille de légumes grillés, oignons rouges, ail, fines herbes".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "75".to_string(),
                id_resto: "4".to_string(),
                name: "Sandwich ciabatta végétarien".to_string(),
                description: "Pain ciabatta betterave, tempeh mariné, salade de choux et carottes, coriandre fraiche, sauce gingembre".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "76".to_string(),
                id_resto: "4".to_string(),
                name: "Sandwich panini jambon".to_string(),
                description: "Pain panini, jambon blanc, cheddar fort, salade, mayon-naise moutardée".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "77".to_string(),
                id_resto: "4".to_string(),
                name: "Sandwich panini poulet grillé".to_string(),
                description: "Pain panini, poulet grillé, tomates, salade, cheddard blanc, mayonnaise tomates séchées".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "78".to_string(),
                id_resto: "4".to_string(),
                name: "Sandwich panini roti de boeuf".to_string(),
                description: "Pain panini carottes, rôti de bœuf, oignons caramélisés, salade, rémoulade céleri & carottes".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "79".to_string(),
                id_resto: "4".to_string(),
                name: "Sandwich panini roti de porc".to_string(),
                description: "Pain panini, rôti de porc, cornichons à l’aneth, salade, cheddar fort, mayonnaise moutardée".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "80".to_string(),
                id_resto: "4".to_string(),
                name: "Sandwich au jambon".to_string(),
                description: "Simple".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "81".to_string(),
                id_resto: "4".to_string(),
                name: "Sandwich au poulet".to_string(),
                description: "Simple".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "82".to_string(),
                id_resto: "4".to_string(),
                name: "Sandwich au oeufs".to_string(),
                description: "Simple".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "83".to_string(),
                id_resto: "4".to_string(),
                name: "Bol kale kimchi".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "84".to_string(),
                id_resto: "4".to_string(),
                name: "Bol kale toscana".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "85".to_string(),
                id_resto: "4".to_string(),
                name: "Bol fèves noires".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "86".to_string(),
                id_resto: "4".to_string(),
                name: "Bol kale césar".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "87".to_string(),
                id_resto: "4".to_string(),
                name: "Wrap dragon".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "88".to_string(),
                id_resto: "4".to_string(),
                name: "Wrap tempeh bbq".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "89".to_string(),
                id_resto: "4".to_string(),
                name: "Wrap végépaté".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "90".to_string(),
                id_resto: "4".to_string(),
                name: "Wrap mekong".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "91".to_string(),
                id_resto: "5".to_string(),
                name: "Salade repas paysanne".to_string(),
                description: "Jambon et oeufs".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "92".to_string(),
                id_resto: "5".to_string(),
                name: "Salade repas océane".to_string(),
                description: "poisson".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "93".to_string(),
                id_resto: "5".to_string(),
                name: "Salade repas végétarienne".to_string(),
                description: "du vert".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "94".to_string(),
                id_resto: "5".to_string(),
                name: "Salade composée d'orzo".to_string(),
                description: "Orzo, pommes Empire, céleri vert, persil, emmental, concombres, menthe, vinaigrette miel & citron".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "95".to_string(),
                id_resto: "5".to_string(),
                name: "Salade composée légumineuses".to_string(),
                description: "Mélange de légumineuses, poivrons rouges, maïs en grains, céleri, écha-lotes vertes, tomates, vinaigrette balsamique".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "96".to_string(),
                id_resto: "5".to_string(),
                name: "Salade composée riz 7 grains".to_string(),
                description: "Riz 7 grains, ratatouille de légumes grillés, oignons rouges, ail, fines herbes".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "97".to_string(),
                id_resto: "5".to_string(),
                name: "Ciabatta thon".to_string(),
                description: "Pain ciabatta, thon à huile d’olive, salade, tomates, mayonnaise".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "98".to_string(),
                id_resto: "5".to_string(),
                name: "Sandwich au jambon".to_string(),
                description: "Simple".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "99".to_string(),
                id_resto: "5".to_string(),
                name: "Sandwich au poulet".to_string(),
                description: "Simple".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "100".to_string(),
                id_resto: "5".to_string(),
                name: "Sandwich au oeufs".to_string(),
                description: "Simple".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "101".to_string(),
                id_resto: "5".to_string(),
                name: "Soucoupe au fromage".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "102".to_string(),
                id_resto: "5".to_string(),
                name: "Soucoupe épinard & féta".to_string(),
                description: "".to_string(),
                vege: true,
                price: 10.,
            },
            MenuItem {
                id: "103".to_string(),
                id_resto: "5".to_string(),
                name: "Soucoupe poulet".to_string(),
                description: "".to_string(),
                vege: false,
                price: 10.,
            },
            MenuItem {
                id: "104".to_string(),
                id_resto: "5".to_string(),
                name: "Soucoupe saucisses".to_string(),
                description: "".to_string(),
                vege: false,
                price: 10.,
            },
        ];

        let orders = vec![
            Order {
                id: "0".to_string(),
                menu_item_ids: vec!["22".to_string()],
                date: chrono::Local.ymd(2020, 1, 8).and_hms_milli(9, 10, 11, 12),
            }
        ];

        AppData {
            data: Arc::new(Mutex::new(Data { restos, plats, orders, delivery_pos: Position { lat: 45.5044624, lon: -73.614625, alt: 105., accr: 16.04, accv: 2.09, speed: 0.7} }))
        }
    }
}